name: MetalCamera

options:
  xcodeVersion: 11.0
  deploymentTarget:
    iOS: 15.0

settings:
  MARKETING_VERSION: 1.0.0
  CURRENT_PROJECT_VERSION: 1

packages:
  SnapKit:
    url: https://github.com/SnapKit/SnapKit
    from: 5.6.0

targets:
  MetalCamera:
    type: application
    platform: iOS
    sources:
      - path: MetalCamera
        excludes: [Info.plist]
    resources:
      - path: MetalCamera/Resources
    info:
      path: MetalCamera/Info.plist
      properties:
        CFBundleName: $(PRODUCT_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        UISupportedInterfaceOrientations~iphone: [UIInterfaceOrientationPortrait, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        UISupportedInterfaceOrientations~ipad: [UIInterfaceOrientationPortrait, UIInterfaceOrientationPortraitUpsideDown, UIInterfaceOrientationLandscapeLeft, UIInterfaceOrientationLandscapeRight]
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UIApplicationSupportsIndirectInputEvents: YES
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: NO
        LSRequiresIPhoneOS: YES
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundlePackageType: $(PRODUCT_BUNDLE_PACKIAGE_TYPE)
        UILaunchScreen:
          UILaunchScreen:
        CFBundleDevelopmentRegion: $(DEVELOPMENT_LANGUAGE)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        NSCameraUsageDescription: "카메라 사용을 허용해주세요"
    settings:
      base:
        DEVELOPMENT_TEAM: 5HZQ3M82FA
        INFOPLIST_FILE: MetalCamera/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.seunghun.MetalCamera
        DISPLAY_NAME: MetalCamera
    dependencies:
      - package: SnapKit
        product: SnapKit
